### ISSUE TITLE
Swtich to TOML configuration file

### ISSUE THREAD

**Issue by Kogia-sima** [rust-sailfish/sailfish#44]
# Description

Since `yaml-rust` crate seems to be no longer actively maintained, we have better switch to `TOML` configuration.

# Example

```toml
template_dirs = ["templates"]
escape = true
delimiter = "%"

[optimization]
rm_whitespace = false
```

c.f. https://github.com/Kogia-sima/sailfish/issues/38#issuecomment-751968542
